title: Atlas Jekyll Theme
desciption: >
  A jekyll theme for personal website.
email: yourusername@gmail.com
baseurl: "/atlas-jekyll-theme" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://dase314.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Jekyll
markdown: kramdown
page_excerpts: true
favicon: "/img/atlas.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
